[package]
name = "chat"
version.workspace = true
edition.workspace = true

[dependencies]
bevy_p2p = { path = "../bevy_p2p" }
bevy = { workspace = true, default-features=true }
tokio = { version = "1.47.1", features = ["full"] }
